#define FSELECT 3  	/* TREE */
#define DIRSTR 3  	/* OBJECT in TREE #3 */
#define SELSTR 21  	/* OBJECT in TREE #3 */
#define FILEBOX 4  	/* OBJECT in TREE #3 */
#define DIRBOX 6  	/* OBJECT in TREE #3 */
#define UPFILE 19  	/* OBJECT in TREE #3 */
#define DNFILE 18  	/* OBJECT in TREE #3 */
#define SCRBAR 16  	/* OBJECT in TREE #3 */
#define FSELGO 22  	/* OBJECT in TREE #3 */
#define FSELCAN 23  	/* OBJECT in TREE #3 */
#define SLIDEBOX 17  	/* OBJECT in TREE #3 */
#define ABSTOOLS 1  	/* TREE */
#define ABOKBUT 7  	/* OBJECT in TREE #1 */
#define SEARCH 4  	/* TREE */
#define SEAOK 3  	/* OBJECT in TREE #4 */
#define SEACAN 5  	/* OBJECT in TREE #4 */
#define FORMAT 5  	/* TREE */
#define FORMOK 5  	/* OBJECT in TREE #5 */
#define FORMCAN 4  	/* OBJECT in TREE #5 */
#define COMPDISK 6  	/* TREE */
#define SSTRING 4  	/* OBJECT in TREE #4 */
#define HSTRING1 7  	/* OBJECT in TREE #4 */
#define FINDFILE 7  	/* TREE */
#define FILESTAT 8  	/* TREE */
#define DISKLAB 9  	/* TREE */
#define DISKERR 10  	/* TREE */
#define RENAME 11  	/* TREE */
#define COMPODRA 4  	/* OBJECT in TREE #6 */
#define COMPODRB 8  	/* OBJECT in TREE #6 */
#define COMPDDRA 6  	/* OBJECT in TREE #6 */
#define COMPDDRB 10  	/* OBJECT in TREE #6 */
#define COMPOK 12  	/* OBJECT in TREE #6 */
#define FINDFNAM 3  	/* OBJECT in TREE #7 */
#define FINDOK 2  	/* OBJECT in TREE #7 */
#define FINDCAN 4  	/* OBJECT in TREE #7 */
#define FAHFILE 1  	/* OBJECT in TREE #8 */
#define FASFILE 3  	/* OBJECT in TREE #8 */
#define FAROFILE 5  	/* OBJECT in TREE #8 */
#define FAAFILE 7  	/* OBJECT in TREE #8 */
#define FATIME 9  	/* OBJECT in TREE #8 */
#define FADATE 11  	/* OBJECT in TREE #8 */
#define FAOK 10  	/* OBJECT in TREE #8 */
#define FACAN 12  	/* OBJECT in TREE #8 */
#define DLABSTR 2  	/* OBJECT in TREE #9 */
#define DLABOK 3  	/* OBJECT in TREE #9 */
#define DLABCAN 4  	/* OBJECT in TREE #9 */
#define REDISK 2  	/* OBJECT in TREE #10 */
#define RETRACK 6  	/* OBJECT in TREE #10 */
#define RETRNUM 4  	/* OBJECT in TREE #10 */
#define REOK 7  	/* OBJECT in TREE #10 */
#define RECAN 8  	/* OBJECT in TREE #10 */
#define RENNNAME 2  	/* OBJECT in TREE #11 */
#define RENOK 4  	/* OBJECT in TREE #11 */
#define RENCAN 3  	/* OBJECT in TREE #11 */
#define GRELA 12  	/* TREE */
#define GRELDEC 3  	/* OBJECT in TREE #12 */
#define GRELOK 2  	/* OBJECT in TREE #12 */
#define GRELCAN 4  	/* OBJECT in TREE #12 */
#define GOABS 13  	/* TREE */
#define GABOK 8  	/* OBJECT in TREE #13 */
#define GABCAN 9  	/* OBJECT in TREE #13 */
#define GOFF 14  	/* TREE */
#define GOFFPLUS 5  	/* OBJECT in TREE #14 */
#define GOFFMINU 6  	/* OBJECT in TREE #14 */
#define GOFFDEC 3  	/* OBJECT in TREE #14 */
#define GOFFOK 2  	/* OBJECT in TREE #14 */
#define GOFFCAN 4  	/* OBJECT in TREE #14 */
#define GABTRACK 2  	/* OBJECT in TREE #13 */
#define GABSECT 3  	/* OBJECT in TREE #13 */
#define MAINMENU 0  	/* TREE */
#define EDITMENU 2  	/* TREE */
#define MENU1S1 10  	/* OBJECT in TREE #0 */
#define MENU2S1 19  	/* OBJECT in TREE #0 */
#define MENU2S2 20  	/* OBJECT in TREE #0 */
#define MENU2S3 21  	/* OBJECT in TREE #0 */
#define MENU2S4 22  	/* OBJECT in TREE #0 */
#define MENU2S5 23  	/* OBJECT in TREE #0 */
#define MENU2S6 24  	/* OBJECT in TREE #0 */
#define MENU2S7 25  	/* OBJECT in TREE #0 */
#define MENU2S8 26  	/* OBJECT in TREE #0 */
#define MENU2S9 27  	/* OBJECT in TREE #0 */
#define MENU2S10 28  	/* OBJECT in TREE #0 */
#define MENU2S11 29  	/* OBJECT in TREE #0 */
#define MENU2S13 31  	/* OBJECT in TREE #0 */
#define MENU3S1 33  	/* OBJECT in TREE #0 */
#define MENU3S2 34  	/* OBJECT in TREE #0 */
#define MENU3S3 35  	/* OBJECT in TREE #0 */
#define MENU3S4 36  	/* OBJECT in TREE #0 */
#define MENU3S5 37  	/* OBJECT in TREE #0 */
#define MENU3S6 38  	/* OBJECT in TREE #0 */
#define MENU3S7 39  	/* OBJECT in TREE #0 */
#define MENU3S8 40  	/* OBJECT in TREE #0 */
#define MENU3S9 41  	/* OBJECT in TREE #0 */
#define MENU3S10 42  	/* OBJECT in TREE #0 */
#define MENU4S1 44  	/* OBJECT in TREE #0 */
#define MENU4S2 45  	/* OBJECT in TREE #0 */
#define MENU4S3 46  	/* OBJECT in TREE #0 */
#define MENU4S4 47  	/* OBJECT in TREE #0 */
#define MENU4S5 48  	/* OBJECT in TREE #0 */
#define MENU4S6 49  	/* OBJECT in TREE #0 */
#define MENU4S7 50  	/* OBJECT in TREE #0 */
#define MENU5S1 53  	/* OBJECT in TREE #0 */
#define MENU5S2 54  	/* OBJECT in TREE #0 */
#define MENU5S3 55  	/* OBJECT in TREE #0 */
#define MENU5S9 62  	/* OBJECT in TREE #0 */
#define EMEN1S1 10  	/* OBJECT in TREE #2 */
#define EMEN2S1 19  	/* OBJECT in TREE #2 */
#define EMEN2S2 20  	/* OBJECT in TREE #2 */
#define EMEN2S3 21  	/* OBJECT in TREE #2 */
#define EMEN4S1 34  	/* OBJECT in TREE #2 */
#define EMEN4S2 35  	/* OBJECT in TREE #2 */
#define EMEN4S3 36  	/* OBJECT in TREE #2 */
#define EMEN4S4 37  	/* OBJECT in TREE #2 */
#define EMEN4S5 38  	/* OBJECT in TREE #2 */
#define EMEN4S6 39  	/* OBJECT in TREE #2 */
#define EMEN4S7 40  	/* OBJECT in TREE #2 */
#define EMEN5S1 42  	/* OBJECT in TREE #2 */
#define EMEN5S2 43  	/* OBJECT in TREE #2 */
#define EMEN5S3 44  	/* OBJECT in TREE #2 */
#define EMEN5S9 51  	/* OBJECT in TREE #2 */
#define FORMDBL 7  	/* OBJECT in TREE #5 */
#define FORMSING 6  	/* OBJECT in TREE #5 */
#define FORMSTR1 1  	/* OBJECT in TREE #5 */
#define GABSIDE1 4  	/* OBJECT in TREE #13 */
#define DIRSORT 15  	/* TREE */
#define SORTNAME 2  	/* OBJECT in TREE #15 */
#define SORTEXT 6  	/* OBJECT in TREE #15 */
#define SORTDATE 4  	/* OBJECT in TREE #15 */
#define SORTTIME 8  	/* OBJECT in TREE #15 */
#define SORTOK 10  	/* OBJECT in TREE #15 */
#define SORTCAN 11  	/* OBJECT in TREE #15 */
#define COMPSTR 1  	/* OBJECT in TREE #6 */
#define VERIFY 16  	/* TREE */
#define VERIOK 4  	/* OBJECT in TREE #16 */
#define VERICAN 3  	/* OBJECT in TREE #16 */
#define FSELSEL 24  	/* OBJECT in TREE #3 */
#define FSELDSEL 25  	/* OBJECT in TREE #3 */
#define FORMBAR 8  	/* OBJECT in TREE #5 */
#define COMPBAR1 13  	/* OBJECT in TREE #6 */
#define VERIBAR 5  	/* OBJECT in TREE #16 */
#define COMPBAR2 15  	/* OBJECT in TREE #6 */
#define COMPCAN 14  	/* OBJECT in TREE #6 */
#define MENU2S12 30  	/* OBJECT in TREE #0 */
#define MENU4S8 51  	/* OBJECT in TREE #0 */
#define PRINT 17  	/* TREE */
#define PRINTCH1 4  	/* OBJECT in TREE #17 */
#define PRINTCH2 5  	/* OBJECT in TREE #17 */
#define PRINTOK 3  	/* OBJECT in TREE #17 */
#define PRINTCAN 7  	/* OBJECT in TREE #17 */
#define PRINTST1 1  	/* OBJECT in TREE #17 */
#define PRINTST2 2  	/* OBJECT in TREE #17 */
#define PRINTST3 6  	/* OBJECT in TREE #17 */
#define GABSIDE2 6  	/* OBJECT in TREE #13 */
#define SSHEAD 2  	/* OBJECT in TREE #4 */
#define HSHEAD 6  	/* OBJECT in TREE #4 */
#define UNERASE 18  	/* TREE */
#define UNENAME 3  	/* OBJECT in TREE #18 */
#define UNEAUTO 6  	/* OBJECT in TREE #18 */
#define UNEMANU 1  	/* OBJECT in TREE #18 */
#define UNEOK 4  	/* OBJECT in TREE #18 */
#define UNECAN 5  	/* OBJECT in TREE #18 */
#define EMEN2S4 22  	/* OBJECT in TREE #2 */
#define FSNAME1 7  	/* OBJECT in TREE #3 */
#define FSNAME2 8  	/* OBJECT in TREE #3 */
#define FSNAME3 9  	/* OBJECT in TREE #3 */
#define FSNAME4 10  	/* OBJECT in TREE #3 */
#define FSNAME5 11  	/* OBJECT in TREE #3 */
#define FSNAME6 12  	/* OBJECT in TREE #3 */
#define FSNAME7 13  	/* OBJECT in TREE #3 */
#define FSNAME8 14  	/* OBJECT in TREE #3 */
#define FSNAME9 15  	/* OBJECT in TREE #3 */
#define MAPPING 19  	/* TREE */
#define DIRCLOSE 5  	/* OBJECT in TREE #3 */
#define MENU5S4 56  	/* OBJECT in TREE #0 */
#define MENU5S5 57  	/* OBJECT in TREE #0 */
#define MENU5S6 58  	/* OBJECT in TREE #0 */
#define MENU5S7 59  	/* OBJECT in TREE #0 */
#define MENU5S8 60  	/* OBJECT in TREE #0 */
#define EMEN5S4 45  	/* OBJECT in TREE #2 */
#define EMEN5S5 46  	/* OBJECT in TREE #2 */
#define EMEN5S6 47  	/* OBJECT in TREE #2 */
#define EMEN5S7 48  	/* OBJECT in TREE #2 */
#define EMEN5S8 49  	/* OBJECT in TREE #2 */
#define MAPBOX 1  	/* OBJECT in TREE #19 */
#define SHOWFILE 20  	/* TREE */
#define SFHEAD 1  	/* OBJECT in TREE #20 */
#define SFFILE1 2  	/* OBJECT in TREE #20 */
#define FSHEAD 14  	/* OBJECT in TREE #8 */
#define SFFILE2 3  	/* OBJECT in TREE #20 */
#define EMEN2S5 24  	/* OBJECT in TREE #2 */
#define EMEN3S1 27  	/* OBJECT in TREE #2 */
#define EMEN3S3 26  	/* OBJECT in TREE #2 */
#define EMEN3S5 28  	/* OBJECT in TREE #2 */
#define MAPHEAD 7  	/* OBJECT in TREE #19 */
#define MAPINFO 8  	/* OBJECT in TREE #19 */
#define DIRSHOW 21  	/* TREE */
#define DSDIRSTR 2  	/* OBJECT in TREE #21 */
#define DSNEXT 3  	/* OBJECT in TREE #21 */
#define DSSTOP 4  	/* OBJECT in TREE #21 */
#define DSHEAD 1  	/* OBJECT in TREE #21 */
#define FSELHEAD 1  	/* OBJECT in TREE #3 */
#define DBINFO 22  	/* TREE */
#define DBFNOT 3  	/* OBJECT in TREE #22 */
#define DBFNSPT 4  	/* OBJECT in TREE #22 */
#define DBFHEAD 2  	/* OBJECT in TREE #22 */
#define DBFNSD 5  	/* OBJECT in TREE #22 */
#define FNSIDES1 6  	/* OBJECT in TREE #22 */
#define FNSIDES2 7  	/* OBJECT in TREE #22 */
#define DBFCHANG 9  	/* OBJECT in TREE #22 */
#define DBFTEMP 10  	/* OBJECT in TREE #22 */
#define DBFCAN 11  	/* OBJECT in TREE #22 */
#define DBIHEAD 12  	/* OBJECT in TREE #22 */
#define DBFSLASH 8  	/* OBJECT in TREE #22 */
#define DBIOK 13  	/* OBJECT in TREE #22 */
#define FAT1SEC 14  	/* OBJECT in TREE #22 */
#define FAT2SEC 16  	/* OBJECT in TREE #22 */
#define RDSEC 15  	/* OBJECT in TREE #22 */
#define DAFSEC 17  	/* OBJECT in TREE #22 */
#define NDSECS 18  	/* OBJECT in TREE #22 */
#define EMEN3S6 30  	/* OBJECT in TREE #2 */
#define EMEN3S2 31  	/* OBJECT in TREE #2 */
#define EMEN3S4 32  	/* OBJECT in TREE #2 */
